# Definir las variables entre {} en un archivo ".env"
services:

  pelicula_db:
    image: postgres
    environment:
      POSTGRES_USER: ${PELICULAS_DB_USER}
      POSTGRES_PASSWORD: ${PELICULAS_DB_PASS}
      POSTGRES_DB: ${PELICULAS_DB_SCHEME}
    ports:
      - "${PELICULAS_DB_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PELICULAS_PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PELICULAS_PG_PASS}
    ports:
      - "${PELICULAS_PG_PORT}:80"  # pgAdmin será accesible en http://localhost:5050
    depends_on:
      - pelicula_db

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /mtn/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASS}
      MINIO_URL: http://localhost:${MINIO_BACK_PORT}
    ports:
      - "${MINIO_BACK_PORT}:9000"
      - "${MINIO_FRONT_PORT}:9001"
    volumes:
      - type: bind
        source: ./minio/data
        target: /mtn/data
      - type: bind
        source: ./minio/etc
        target: /etc/config.env