services:
  hoppscotch-backend:
    image: elestio/hoppscotch-backend:latest
    env_file:
      - ./.env
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:${ADMIN_PASSWORD}@hoppscotch-db:5432/hoppscotch?connect_timeout=300
      - PORT=8080
    depends_on:
      - hoppscotch-db
    ports:
      - "3011:8080"  # Usando puerto 3011 en lugar de 3170

  hoppscotch-app:
    image: elestio/hoppscotch-app:latest
    env_file:
      - ./.env
    depends_on:
      - hoppscotch-backend
    ports:
      - "3012:3000"  # Usando puerto 3012 en lugar de 3130

  hoppscotch-sh-admin:
    image: elestio/hoppscotch-sh-admin:latest
    env_file:
      - ./.env
    depends_on:
      - hoppscotch-backend
    ports:
      - "3013:3100"  # Usando puerto 3013 en lugar de 3100

  hoppscotch-db:
    image: elestio/postgres:15
    ports:
      - "3014:5432"  # Usando puerto 3014 en lugar de 5282
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
      POSTGRES_DB: hoppscotch
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
