# Definir las variables entre {} en un archivo ".env"
services:

  pelicula_db:
    image: postgres
    environment:
      POSTGRES_USER: ${PELICULAS_DB_USER}
      POSTGRES_PASSWORD: ${PELICULAS_DB_PASS}
      POSTGRES_DB: ${PELICULAS_DB_SCHEME}
    ports:
      - "${PELICULAS_DB_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PELICULAS_PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PELICULAS_PG_PASS}
    ports:
      - "${PELICULAS_PG_PORT}:80"  # pgAdmin será accesible en http://localhost:5050
    depends_on:
      - pelicula_db

  gateway:
    image: hmunoz79/apigateway:1.5
    extra_hosts:
      - "host.docker.internal:${IP_HOST}" # Mi IP
    ports:
      - "${API_GATEWAY_PORT}:9500" # Desde el FrontEnd
    environment:
      SPRING_SERVER_PORT: 9500
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://host.docker.internal:${PELICULAS_PORT}
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: service-almacen # MS Peliculas
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path= /almacen/**
      SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERS[0]: StripPrefix=1
      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: http://host.docker.internal:${VENTAS_PORT}
      SPRING_CLOUD_GATEWAY_ROUTES[1]_ID: service-transacciones # MS Ventas
      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]: Path= /gateway/**
      SPRING_CLOUD_GATEWAY_ROUTES[1]_FILTERS[0]: StripPrefix=1

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /mtn/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASS}
      MINIO_URL: http://localhost:${MINIO_BACK_PORT}
    ports:
      - "${MINIO_BACK_PORT}:9000"
      - "${MINIO_FRONT_PORT}:9001"
    volumes:
      - type: bind
        source: ./minio/data
        target: /mtn/data
      - type: bind
        source: ./minio/etc
        target: /etc/config.env


  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_CLIENT_PORT}:5672"  # Puerto de RabbitMQ para el cliente
      - "${RABBITMQ_INTERFACE}:15672"  # Puerto de la interfaz de gestión
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - ./rabi:/var/lib/rabbitmq

  redis:
    container_name: peliculas-redis
    image: redis
    ports:
      - "3310:6379"