# Definir las variables entre {} en un archivo ".env"
services:
  pelicula_db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: pelicula_db
    ports:
      - "5002:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  # pgAdmin será accesible en http://localhost:5050
    depends_on:
      - pelicula_db

  gateway:
    image: hmunoz79/apigateway:1.5
    extra_hosts:
      - "host.docker.internal:${IP_HOST}" # Mi IP
    ports:
      - "9500:9500" # Desde el FrontEnd
    environment:
      SPRING_SERVER_PORT: 9500
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://host.docker.internal:8080
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: service-almacen # MS Peliculas
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path= /almacen/**
      SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERS[0]: StripPrefix=1
      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: http://host.docker.internal:8081
      SPRING_CLOUD_GATEWAY_ROUTES[1]_ID: service-transacciones # MS Ventas
      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]: Path= /gateway/**
      SPRING_CLOUD_GATEWAY_ROUTES[1]_FILTERS[0]: StripPrefix=1