scrape_configs:
  - job_name: 'spring-boot-application'
    metrics_path: '/management/prometheus'
    scrape_interval: 3s # This can be adjusted based on our needs
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'My Spring Boot Application'