application:
  title: Almacen de Peliculas
  ms_name: Peliculas
  version: Sprint 4
  author: Carlos Farra
  lastUpdate: Sabado 02 de Noviembre 2024

server:
  port: 8081

spring:
  application:
    name: pelicula
  datasource:
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db-name}
    username: user
    password: "1111"
    host: localhost
    port: 5002
    db-name: pelicula_db
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://k8s-lia.unrn.edu.ar/keycloak/realms/videoclub02
          jwk-set-uri: https://k8s-lia.unrn.edu.ar/keycloak/realms/videoclub02/protocol/openid-connect/certs
  jmx:
    enabled: true
  rabbitmq:
    host: k8s-lia.unrn.edu.ar
    port: 30567
    username: taller
    password: taller.2024


springdoc:
  api-docs:
    path: /api-docs

minio:
  endpoint: http://localhost:9000
  user: admin
  pass: 12345678
  bucket:
    grande: portada-grande
    pequeno: portada-pequena

rabbitmq:
  event:
    exchange:
      name: exchange_videocloud02
      users: keycloaktaller
    movie:
      queue:
        name: movieQueue
      routing:
        key: Pelicula.#
    actor:
      queue:
        name: actorQueue
      routing:
        key: Actor.#
    usuario:
      queue:
        name: videoclub02
      routing:
        key: KK.EVENT.*.videoclub02.#

page_tam:
  pelicula: 10
