spring:
  application:
    name: pelicula
  datasource:
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db-name}
    username: user
    password: "1111"
    host: localhost
    port: 5002
    db-name: pelicula_db
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://k8s-lia.unrn.edu.ar/keycloak/realms/videoclub02
          jwk-set-uri: https://k8s-lia.unrn.edu.ar/keycloak/realms/videoclub02/protocol/openid-connect/certs
  jmx:
    enabled: true

# Enable Actuator endpoints in application.yml
management:
  endpoints:
    web:
      base-path: "/management"
      exposure:
        include: "*"
        exclude: "beans"
    jmx:
      exposure:
        include: "*"




application:
  title: Almacen de Peliculas
  ms_name: Peliculas
  version: Sprint 2
  author: Carlos Farra
  lastUpdate: Sabado 21 de Septiembre 2024

# Variables para manejar el tamaño de las paginas
tam_page_pelicula: 10

# Variables de Imagen
file_path_images_p: ./imagen/pequenas/
file_path_images_g: ./imagen/grandes/
